const letterA1 = document.querySelector('#letter-a1');
const letterN1 = document.querySelector('#letter-n1');
const letterI1 = document.querySelector('#letter-i1');
const letterM = document.querySelector('#letter-m');
const letterA2 = document.querySelector('#letter-a2');
const letterT1 = document.querySelector('#letter-t');
const letterI2 = document.querySelector('#letter-i2');
const letterO = document.querySelector('#letter-o');
const letterN2 = document.querySelector('#letter-n2');
const letterS = document.querySelector('#letter-s');
const letterF = document.querySelector('#for');
const letterT2 = document.querySelector('#the');
const letterW = document.querySelector('#win');
const dot1 = document.querySelector('#dot-1');
const dot2 = document.querySelector('#dot-2');

gsap.from(letterN1, { y: 10000, duration: 1.5 });
gsap.from(letterI1, { y: 10000, duration: 1.5, delay: 0.8 });
gsap.from(letterM, { y: 10000, duration: 1.5, delay: 1 });
gsap.from(letterA2, { y: 10000, duration: 1.5, delay: 1.2 });
gsap.from(letterT1, { y: 10000, duration: 1.5, delay: 1.4 });
gsap.from(letterI2, { y: 10000, duration: 1.5, delay: 1.6 });
gsap.from(letterO, { y: 10000, duration: 1.5, delay: 1.8 });
gsap.from(letterN2, { y: 10000, duration: 1.5, delay: 2 });
gsap.from(letterS, { y: 10000, duration: 1.5, delay: 2.2 });
gsap.from(letterF, { y: 10000, duration: 1.5, delay: 2.4 });
gsap.from(letterT2, { y: 10000, duration: 1.5, delay: 2.6 });
gsap.from(letterW, { x: 2000, duration: 2, delay: 2.8 });
gsap.from(letterA1, { x: -2000, duration: 2, delay: 2.8 });
gsap.from(dot1, { y: 10000, duration: 2, ease: 'bounce.out', delay: 3 });
gsap.from(dot2, { y: 10000, duration: 2, ease: 'bounce.out', delay: 3 });
